services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./db/mongodb:/data/db
    networks:
      - miskatonic
  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - miskatonic
    depends_on:
      mongo:
        condition: service_started
  miskatonic-backend:
    container_name: miskatonicback
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.back
    volumes:
      - ./backend:/usr/src/app
      - .env:/usr/src/app/.env
      - ./promtail-logs:/var/log
    networks:
      - miskatonic
    depends_on:
      mongo:
        condition: service_started
  miskatonic-frontend:
    container_name: miskatonicfront
    ports:
      - 8082:8082
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - ./frontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - miskatonic
    depends_on:
      mongo:
        condition: service_started
      miskatonic-backend:
        condition: service_started

  # Prometheus/Grafana config with cAdvisor and redis
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - loki
    networks:
      - miskatonic
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
    networks:
      - miskatonic
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    # - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    networks:
      - miskatonic
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    networks:
      - miskatonic
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(run|var/lib/docker/.+)($|/)' 
      - '--collector.filesystem.ignored-fs-types=tmpfs,devtmpfs'
    network_mode: host
    pid: host
    ports:
    - 9100:9100
    depends_on:
    - grafana
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
  loki:
    container_name: loki
    image: grafana/loki
    ports:
      - 3100:3100
    volumes:
      - ./loki.yml:/etc/loki/loki-config.yaml
    networks:
      - miskatonic
  promtail:
    container_name: promtail
    image: grafana/promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - ./promtail-logs:/var/log
    depends_on:
      - loki
    networks:
      - miskatonic

networks:
  miskatonic:
    driver:
      bridge