{
 "title": "MiskatonicBoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consommation RAM en GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=~\"miskatonic-frontend|mongo|mongo-express|miskatonic-backend\"} / 1000000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requêtes totale (par minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval]) * 60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Charge CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{container_label_com_docker_compose_service=~\"miskatonic-frontend|mongo|mongo-express|miskatonic-backend\"}[1m]) * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_avail_bytes{instance=\"172.17.0.1:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs (EN COURS)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_requests_created", "legendFormat": "__auto" }
   ]
  }
 ]
}