scrape_configs:
- job_name: cadvisor
  scrape_interval: 1s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: fastapi
  scrape_interval: 1s
  static_configs:
  - targets:
    - miskatonic-backend:8000
- job_name: node_exporter
  scrape_interval: 1s
  static_configs:
  - targets:
    - 172.17.0.1:9100